### ISSUE TITLE
Repositório desatualizado

### ISSUE THREAD

**Issue by hisirdox** [MariaCarolinass/pagina-estatica-dadoslivres#1]
Vejo que o repositório no gitlab está mais atualizado que este,
 o ideal seria deixar os dois iguais, ou escolher um só para trabalhar

**Comment by MariaCarolinass** [comment]
Oii @Nerd0000, esse repositório aqui criei faz um tempo para ser uma página estática, pois eu não tinha o projeto rodando com um banco de dados.

**Comment by MariaCarolinass** [comment]
@Nerd0000, hoje o projeto cresceu e te convido a conhecer acessando em dadoslivres.org. Também entrar para o nosso grupo no Telegram @DadosLivres, se entrar lá manda um "oi" :)

**Comment by MariaCarolinass** [comment]
Eu comecei a desenvolver o projeto na plataforma do [GitHub](https://github.com/pbaesse/plataforma-livre-dados-abertos) mas decidimos migrar o projeto para o GitLab por ser uma plataforma Software Livre. A gente deixa o repositório salvo no GitHub por questões de visibilidade.

**Comment by hisirdox** [comment]
Entendi
